-- Industries: 68 v3-canonical values. Stored as a seeded table rather
-- than an enum so admins can add/edit without a migration.

create table public.industries (
  slug text primary key,
  display_name text not null unique,
  active boolean not null default true,
  display_order int,
  created_at timestamptz not null default now()
);

-- RLS: industries are public reference data
alter table public.industries enable row level security;
create policy industries_select_all on public.industries for select using (true);

-- Seed with all 68 values from v3 (matching exact text from
-- v3-archive/server/src/utilities/validateRequest.ts).
insert into public.industries (slug, display_name) values
  ('affiliate-marketing-networks', 'Affiliate marketing networks'),
  ('artificial-intelligence-and-machine-learning-companies', 'Artificial intelligence and machine learning companies'),
  ('cloud-storage-and-hosting-services', 'Cloud storage and hosting services'),
  ('content-marketing-agencies', 'Content marketing agencies'),
  ('cryptocurrency-and-blockchain-companies', 'Cryptocurrency and blockchain companies'),
  ('customer-relationship-management-crm-software-vendors', 'Customer relationship management (CRM) software vendors'),
  ('cybersecurity-software-providers', 'Cybersecurity software providers'),
  ('data-analytics-and-business-intelligence-firms', 'Data analytics and business intelligence firms'),
  ('digital-marketing-agencies', 'Digital marketing agencies'),
  ('e-commerce-platforms', 'E-commerce platforms'),
  ('e-learning-platforms-and-learning-management-systems-lms', 'E-learning platforms and Learning Management Systems (LMS)'),
  ('e-sports-and-online-gaming-platforms', 'E-sports and online gaming platforms'),
  ('email-marketing-services', 'Email marketing services'),
  ('freelance-marketplaces', 'Freelance marketplaces'),
  ('graphic-design-services', 'Graphic design services'),
  ('influencer-marketing-platforms', 'Influencer marketing platforms'),
  ('internet-of-things-iot-providers', 'Internet of Things (IoT) providers'),
  ('language-learning-platforms', 'Language learning platforms'),
  ('mobile-app-development-companies', 'Mobile app development companies'),
  ('online-advertising-platforms', 'Online advertising platforms'),
  ('online-art-and-design-marketplaces', 'Online art and design marketplaces'),
  ('online-auction-and-marketplace-platforms', 'Online auction and marketplace platforms'),
  ('online-automotive-parts-and-services', 'Online automotive parts and services'),
  ('online-beauty-and-skincare-products', 'Online beauty and skincare products'),
  ('online-course-providers', 'Online course providers'),
  ('online-dating-and-matchmaking-services', 'Online dating and matchmaking services'),
  ('online-food-ordering-and-delivery-platforms', 'Online food ordering and delivery platforms'),
  ('online-fundraising-and-crowdfunding-platforms', 'Online fundraising and crowdfunding platforms'),
  ('online-gardening-and-landscaping-services', 'Online gardening and landscaping services'),
  ('online-gift-and-specialty-product-sales', 'Online gift and specialty product sales'),
  ('online-insurance-providers', 'Online insurance providers'),
  ('online-job-boards', 'Online job boards'),
  ('online-office-supply-and-stationery-sales', 'Online office supply and stationery sales'),
  ('online-payment-processing-companies', 'Online payment processing companies'),
  ('online-recruitment-and-staffing-agencies', 'Online recruitment and staffing agencies'),
  ('online-research-and-data-collection-firms', 'Online research and data collection firms'),
  ('online-specialty-food-and-beverage-sales', 'Online specialty food and beverage sales'),
  ('online-streaming-services-and-content-providers', 'Online streaming services and content providers'),
  ('online-survey-and-polling-tools', 'Online survey and polling tools'),
  ('online-ticketing-and-event-management-platforms', 'Online ticketing and event management platforms'),
  ('online-travel-agencies-and-booking-platforms', 'Online travel agencies and booking platforms'),
  ('online-tutoring-services', 'Online tutoring services'),
  ('podcasting-and-audio-content-platforms', 'Podcasting and audio content platforms'),
  ('project-management-software-providers', 'Project management software providers'),
  ('remote-baby-and-childcare-product-sales', 'Remote baby and childcare product sales'),
  ('remote-book-and-ebook-sales', 'Remote book and eBook sales'),
  ('remote-car-sales-and-leasing-services', 'Remote car sales and leasing services'),
  ('remote-coaching-and-personal-development-services', 'Remote coaching and personal development services'),
  ('remote-customer-support-services', 'Remote customer support services'),
  ('remote-electronics-and-gadget-sales', 'Remote electronics and gadget sales'),
  ('remote-event-planning-services', 'Remote event planning services'),
  ('remote-fashion-and-clothing-sales', 'Remote fashion and clothing sales'),
  ('remote-financial-services-and-banking-platforms', 'Remote financial services and banking platforms'),
  ('remote-healthcare-and-telemedicine-services', 'Remote healthcare and telemedicine services'),
  ('remote-home-improvement-and-maintenance-services', 'Remote home improvement and maintenance services'),
  ('remote-legal-and-consultation-services', 'Remote legal and consultation services'),
  ('remote-music-and-audio-production-services', 'Remote music and audio production services'),
  ('remote-pet-care-and-product-sales', 'Remote pet care and product sales'),
  ('remote-photography-and-image-editing-services', 'Remote photography and image editing services'),
  ('remote-public-relations-agencies', 'Remote public relations agencies'),
  ('remote-real-estate-services', 'Remote real estate services'),
  ('remote-sports-and-outdoor-equipment-sales', 'Remote sports and outdoor equipment sales'),
  ('remote-translation-services', 'Remote translation services'),
  ('renewable-energy-technology-firms', 'Renewable energy technology firms'),
  ('search-engine-optimization-seo-companies', 'Search engine optimization (SEO) companies'),
  ('smart-home-technology-vendors', 'Smart home technology vendors'),
  ('social-media-management-firms', 'Social media management firms'),
  ('software-as-a-service-saas-companies', 'Software as a Service (SaaS) companies'),
  ('subscription-box-services', 'Subscription box services'),
  ('telecommunications-providers', 'Telecommunications providers'),
  ('video-production-companies', 'Video production companies'),
  ('virtual-and-remote-collaboration-tools', 'Virtual and remote collaboration tools'),
  ('virtual-assistant-and-chatbot-providers', 'Virtual assistant and chatbot providers'),
  ('virtual-event-platforms', 'Virtual event platforms'),
  ('virtual-fitness-and-wellness-platforms', 'Virtual fitness and wellness platforms'),
  ('virtual-office-space-providers', 'Virtual office space providers'),
  ('virtual-reality-and-augmented-reality-developers', 'Virtual reality and augmented reality developers'),
  ('web-development-agencies', 'Web development agencies'),
  ('webinar-and-video-conferencing-platforms', 'Webinar and video conferencing platforms'),
  ('website-analytics-and-monitoring-services', 'Website analytics and monitoring services'),
  ('other', 'Other');

comment on table public.industries is
  'Canonical industry list. Seeded from v3 (68 values). Admins can add/deactivate; talent and listings reference by slug.';
